management:
    server:
        port: 9091
    endpoints:
        web:
            exposure:
                include: health,metrics,prometheus
    metrics:
        tags:
            application: ${spring.application.name}

knowledge:
    sync:
        on-startup: true
